security:
  encoders:
    App\Entity\User:
      algorithm: argon2i

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      provider: app_user_provider
      pattern:  ^/
      anonymous: true

      form_login:
        login_path: app_login
        check_path: app_login
        provider: app_user_provider

      remember_me:
        secret:   '%kernel.secret%'
        lifetime: 2592000 # 30 days in seconds
        token_provider: 'Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider'
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
      logout:
        path:  security_logout
        target: app_login

#      role_hierarchy:
#          ROLE_USER: ROLE_USER
#          ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

      access_control:
      - { path: ^/, roles: ROLE_USER }
